name: JSON Web Token (JWT)

branding:
  icon: code
  color: blue

description: >
  Encode/Decode/Sign/Verify JSON Web Tokens with options including masking,
  JSON object dump & more.

inputs:
  algorithm:
    default: HS256
    description: (Encode) Signing algorithm for encoding a new JWT, only HS256 currently supported.
    type: string
  debug:
    default: false
    description: (Decode/Encode) Enable debugging output.
    type: boolean
  enable-display:
    default: false
    description: (Decode/Encode) Enable pretty colorized display of JWT decoded object.
    type: boolean
  enable-fail-on-unverified:
    default: true
    description: (Decode) Fail if the JWT signing cannot be verified.
    type: boolean
  enable-mask-jwt:
    default: false
    description: (Decode/Encode) Enable masking of entire JWT in Actions output.
    type: boolean
  enable-mask-signature:
    default: true
    description: (Decode/Encode) Enable masking of JWT signature in Actions output.
    type: boolean
  header:
    default: |
      alg: ${ALGORITHM}
      typ: JWT
    description: (Encode) Header yq template for encoding a new JWT (JSON or YAML).
    type: string
  jwt:
    description: (Decode) JWT that will be decoded & verified.
    required: false
    type: string
  payload:
    description: (Encode) Payload data structure for encoding a new JWT (JSON or YAML).
    required: false
    type: string
  secret:
    default: your-256-bit-secret
    description: (Decode/Encode) Secret used to sign or verify a signed JWT.
    type: string

outputs:
  algorithm:
    description: Signing algorithm.
    value: ${{ steps.decode.outputs.algorithm }}
  header:
    description: Decoded header in JSON.
    value: ${{ steps.decode.outputs.header }}
  jwt:
    description: Encoded & signed JWT.
    value: ${{ steps.decode.outputs.jwt }}
  payload:
    description: Decoded payload in JSON.
    value: ${{ steps.decode.outputs.payload }}
  signature:
    description: Decoded signature in Base64 (not URL safe Base64).
    value: ${{ steps.decode.outputs.signature }}
  verified:
    description: Boolean-as-string ("true" / "false") indicating if the JWT is verified.
    value: ${{ steps.decode.outputs.verified }}

runs:
  using: composite
  steps:
    - if: runner.debug || inputs.debug == 'true'
      run: |
        # JWT - Debug
        echo ::group::Debug - utility versions
        yq --version
        jq --version
        openssl version
        echo ::endgroup::
      shell: bash

    - env:
        ALGORITHM: ${{ inputs.algorithm }}
        ENABLE_MASK_JWT: ${{ inputs.enable-mask-jwt == 'true' && 'true' || 'false' }}
        ENABLE_MASK_SIGNATURE: ${{ inputs.enable-mask-signature == 'true' && 'true' || 'false' }}
        HEADER: ${{ inputs.header }}
        JQ_LIB_PATH: ${{ github.action_path }}
        PAYLOAD: ${{ inputs.payload }}
        SECRET: ${{ inputs.secret }}
      id: encode
      if: inputs.payload != ''
      run: |
        # JWT - Encode Token
        HEADER=$(yq -o json --expression 'with_entries(.value |= envsubst)' <<<"${HEADER}" | jq -c)
        PAYLOAD=$(yq -o json <<<"${PAYLOAD}" | jq -c)
        if '${{ (runner.debug || inputs.debug == 'true') && 'true' || 'false' }}' ; then
          echo -e "::group::Debug - header\n${HEADER}\n::endgroup::"
          echo -e "::group::Debug - payload\n${PAYLOAD}\n::endgroup::"
        fi
        JWT_UNSIGNED=$(
          jq -n -r -L "$JQ_LIB_PATH" \
            --arg header "$HEADER" \
            --arg payload "$PAYLOAD" \
            ' include "jwt";
              [($header | url_safe_base64_encode), ($payload | url_safe_base64_encode)]
              | join(".")
            '
        )
        SIGNATURE=$(
          echo -n "$JWT_UNSIGNED" |
            openssl dgst -binary -hmac "$SECRET" -sha256 |
            openssl base64 -e -A |
            jq -r -L "$JQ_LIB_PATH" -R 'include "jwt"; url_safe_encode'
        )
        if $ENABLE_MASK_SIGNATURE ; then
          echo "::add-mask::${SIGNATURE}"
        fi
        JWT=$(
          jq -n -r -L "$JQ_LIB_PATH" \
            --arg jwt_unsigned "$JWT_UNSIGNED" \
            --arg signature "$SIGNATURE" \
            'include "jwt"; "\($jwt_unsigned).\($signature)"'
        )
        if $ENABLE_MASK_JWT ; then
          echo "::add-mask::${JWT}"
        fi
        echo -e "jwt<<EOF\n${JWT}\nEOF" >>"${GITHUB_OUTPUT}"
      shell: bash

    - env:
        ENABLE_DISPLAY: ${{ inputs.enable-display == 'true' && 'true' || 'false' }}
        ENABLE_FAIL_ON_UNVERIFIED: ${{ inputs.enable-fail-on-unverified == 'true' && 'true' || 'false' }}
        ENABLE_MASK_JWT: ${{ inputs.enable-mask-jwt == 'true' && 'true' || 'false' }}
        ENABLE_MASK_SIGNATURE: ${{ inputs.enable-mask-signature == 'true' && 'true' || 'false' }}
        JQ_LIB_PATH: ${{ github.action_path }}
        JWT: ${{ inputs.jwt == '' && steps.encode.outputs.jwt || inputs.jwt }}
        SECRET: ${{ inputs.secret }}
      id: decode
      run: |
        # JWT - Decode/Verify Token
        if $ENABLE_MASK_JWT ; then
          echo "::add-mask::${JWT}"
        fi
        if ${{ inputs.secret == 'your-256-bit-secret' && 'true' || 'false' }}  ; then
          echo '::warning title=Unsafe (default) secret used::The secret "your-256-bit-secret",'\
            'which is the default from jwt.io, is being used. This is NOT SAFE for production.'
        fi
        JWT_IS_VALID=$(
          jq -n -r -L "$JQ_LIB_PATH" --arg jwt "$JWT" \
            'include "jwt"; $jwt | validate'
        )
        if [ "$JWT_IS_VALID" != 'true' ] ; then
          echo '::error title=JWT Is Invalid::The JWT provided or generated is invalid (not parseable).'
        fi
        JWT_UNSIGNED=$(
          jq -n -r -L "$JQ_LIB_PATH" --arg jwt "$JWT" \
            'include "jwt"; $jwt | decode_raw.unsigned'
        )
        SIGNATURE=$(
          echo -n "$JWT_UNSIGNED" |
            openssl dgst -binary -hmac "$SECRET" -sha256 |
            openssl base64 -e -A |
            jq -r -L "$JQ_LIB_PATH" -R 'include "jwt"; url_safe_encode'
        )
        if $ENABLE_MASK_SIGNATURE ; then
          echo "::add-mask::${SIGNATURE}"
        fi
        JSON=$(
          jq -n -L "$JQ_LIB_PATH" --arg jwt "$JWT" --arg signature "$SIGNATURE" \
            'include "jwt"; $jwt | verify($signature)'
        )
        if "$ENABLE_DISPLAY" ; then
          echo '::group::JWT Display'
          jq -C . <<<"$JSON"
          echo '::endgroup::'
        fi
        jq -n -r -L "$JQ_LIB_PATH" --arg jwt "$JWT" --arg signature "$SIGNATURE" \
          'include "jwt"; $jwt | verify($signature) | github_output' >>"${GITHUB_OUTPUT}"
        VERIFIED=$(jq -r .verified <<<"${JSON}")
        if "$ENABLE_FAIL_ON_UNVERIFIED" && [ "$VERIFIED" != true ] ; then
          echo '::error title=JWT Failed Verification::Unable to verify the ${{ inputs.algorithm }}' \
            'signed token using the supplied secret.'
        fi
      shell: bash
