name: Test JWT

on:
  push:

jobs:
  Test-JWT:
    name: Test JWT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: jwt-decode
        name: JSON Web Token (JWT) - Decode jwt.io demo token
        uses: ./
        with:
          enable-display: true
          secret: your-256-bit-secret
          jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

      - env:
          JWT_ACTION_OUTPUTS: ${{ toJSON(steps.jwt-decode.outputs) }}
        name: Examine JWT Decode outputs
        run: |
          # Examine JWT Decode outputs
          echo ::group::JWT Decode outputs
          jq -C . <<<"${JWT_ACTION_OUTPUTS}"
          echo ::endgroup::

      - id: jwt-encode
        name: JSON Web Token (JWT) - Encode jwt.io demo token
        uses: ./
        with:
          enable-display: true
          payload: |
            sub: '1234567890'
            name: John Doe
            iat: 1516239022
          secret: 'your-256-bit-secret'

      - env:
          JWT_ACTION_OUTPUTS: ${{ toJSON(steps.jwt-encode.outputs) }}
        name: Examine JWT Encode outputs
        run: |
          # Examine JWT Encode outputs
          echo ::group::JWT Encode outputs
          jq -C . <<<"${JWT_ACTION_OUTPUTS}"
          echo ::endgroup::

      - id: jq
        uses: direct-actions/jq@v1
        with:
          input-command: uuidgen
          filter: |
            {
              exp: (now | round + (60 * 60 * 24 * 7)), # now + 1 week
              iat: (now | round),
              jti: ., # use UUID generated by input-command
              nbf: (now | round + (60 * 60)), # now + 1 hour
            }
          raw-input: true

      - name: JSON Web Token (JWT) - Encode custom token
        uses: ./
        with:
          enable-display: true
          payload: ${{ steps.jq.outputs.output }}
          secret: RaNDoM+S3cR3t
