name: Test JWT

on:
  push:

jobs:
  Test-JWT:
    name: Test JWT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: jwt-decode
        name: JSON Web Token (JWT) - Decode
        uses: ./
        with:
          enable-display: true
          secret: your-256-bit-secret
          jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

      - env:
          JWT_ACTION_OUTPUTS: ${{ toJSON(steps.jwt-decode.outputs) }}
        name: Examine JWT Decode outputs
        run: |
          # Examine JWT Decode outputs
          echo ::group::JWT Decode outputs
          jq -C . <<<"${JWT_ACTION_OUTPUTS}"
          echo ::endgroup::

      - id: jwt-encode
        name: JSON Web Token (JWT) - Encode
        uses: ./
        with:
          enable-display: true
          payload: |
            sub: '1234567890'
            name: John Doe
            iat: 1516239022
          secret: 'your-256-bit-secret'

      - env:
          JWT_ACTION_OUTPUTS: ${{ toJSON(steps.jwt-encode.outputs) }}
        name: Examine JWT Encode outputs
        run: |
          # Examine JWT Encode outputs
          echo ::group::JWT Encode outputs
          jq -C . <<<"${JWT_ACTION_OUTPUTS}"
          echo ::endgroup::
