name: JWT

on:
  workflow_dispatch:
    inputs:
      jwt:
        description: 'JWT (Decode): '
        default: ''
        type: string
      payload:
        description: 'Payload (Encode): '
        default: ''
        type: string
      secret:
        description: 'Secret (Encode/Decode): '
        default: ''
        type: string


jobs:
  JWT:
    name: JWT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: jwt-decode
        name: JSON Web Token (JWT) - Decode jwt.io demo token
        uses: ./
        with:
          enable-display: true
          payload: ${{ inputs.payload }}
          secret: ${{ inputs.secret }}
          jwt: ${{ inputs.jwt }}
